version: '1.0.0'
services:
  blockly-site:
    image: pepperonit/blockly-site
    container_name: blockly-site
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_IP="[Your local ip address]"
      - REACT_APP_SERVER_PORT=5000
      - REACT_APP_ADMIN_NICKNAME="[Your chosen admin username]"
      - REACT_APP_ADMIN_PW="[Your chosen admin password]"